update=16-4-2012 23:57:31
last_client=cvpcb
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=dips-s
LibName12=RJ45-MAG
LibName13=rj45_ethernet
LibName14=w_conn_pc
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
